import type { ImagePropsWithDPrefix } from '@/types';

export const rerenderPropsList = [
  'src',
  'active',
  'disabled',
  'width',
  'height',
  'imgWidth',
  'fillColor',
  'strokeColor',
  'lineWidth',
  'natural',
  'areaKeyName',
  'stayHighlighted',
  'stayMultiHighlighted',
  'toggleHighlighted',
  'parentWidth',
  'responsive',
] as const;

export const imageMapperDefaultProps: Omit<ImagePropsWithDPrefix, 'DSrc' | 'DMap'> = {
  DAreaKeyName: 'id',
  DActive: true,
  DDisabled: false,
  DFillColor: 'rgba(255, 255, 255, 0.5)',
  DStrokeColor: 'rgba(0, 0, 0, 0.5)',
  DLineWidth: 1,
  DImgWidth: 0,
  DWidth: 0,
  DHeight: 0,
  DNatural: false,
  DStayHighlighted: false,
  DStayMultiHighlighted: false,
  DToggleHighlighted: false,
  DRerenderProps: [],
  DResponsive: false,
  DParentWidth: 0,

  DOnImageClick: null,
  DOnImageMouseMove: null,
  DOnClick: null,
  DOnMouseDown: null,
  DOnMouseUp: null,
  DOnTouchStart: null,
  DOnTouchEnd: null,
  DOnMouseMove: null,
  DOnMouseEnter: null,
  DOnMouseLeave: null,
  DOnLoad: null,
};
